# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric extfun craction = 1 color colorerr
color A0:C10 7
color F0:F0 7
fkey 3 = "merge \"|./doit a0:c10 f0 /tmp/data\""
rightstring E0 = "Median:"
rightstring E1 = "(Press F3 to update)"
goto A0 A0
